### ISSUE TITLE
Update & Cleanup README

### ISSUE THREAD

**Issue by tarithj** [tarithj/BubbleSortInEveryLang#10]
This repo is quite self explanatory but it would be better if the README had some information about Bubble sorting and the contributing guidelines should be under a separate heading.

**Comment by tarithj** [comment]
@everly-gif You are welcome to contribute, ill mark this issue as WIP

**Comment by tarithj** [comment]
@everly-gif Nice suggestion! do you want to work on that too? if not we can move that suggestion into another issue

**Comment by everly-gif** [comment]
@tarithj someone else can work on that! :)
